//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueStorageCheck_GUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrueStorageCheck_GUI.Resources.language_de", typeof(language_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgebrochen.
        /// </summary>
        public static string aborted {
            get {
                return ResourceManager.GetString("aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gesamter freier Platz.
        /// </summary>
        public static string all_available_place {
            get {
                return ResourceManager.GetString("all_available_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschn-Lesen.
        /// </summary>
        public static string avg_read {
            get {
                return ResourceManager.GetString("avg_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschn-Schreiben.
        /// </summary>
        public static string avg_write {
            get {
                return ResourceManager.GetString("avg_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisch nach Updates suchen.
        /// </summary>
        public static string check_for_updates {
            get {
                return ResourceManager.GetString("check_for_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log löschen.
        /// </summary>
        public static string clear_log {
            get {
                return ResourceManager.GetString("clear_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie analysieren derzeit ein Gerät. Sind Sie sicher, dass Sie abbrechen und beenden möchten?.
        /// </summary>
        public static string closing_analyzing_confirm {
            get {
                return ResourceManager.GetString("closing_analyzing_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktueller Zustand.
        /// </summary>
        public static string current_state {
            get {
                return ResourceManager.GetString("current_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerät.
        /// </summary>
        public static string device {
            get {
                return ResourceManager.GetString("device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerättest.
        /// </summary>
        public static string device_test {
            get {
                return ResourceManager.GetString("device_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei &quot;TrueStorageCheck.dll&quot; wurde nicht gefunden.
        ///Stellen Sie sicher, dass Sie alle Dateien korrekt heruntergeladen und extrahiert haben..
        /// </summary>
        public static string dll_not_found_text {
            get {
                return ResourceManager.GetString("dll_not_found_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        public static string dll_not_found_title {
            get {
                return ResourceManager.GetString("dll_not_found_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verstrichene Zeit.
        /// </summary>
        public static string elapsed_time {
            get {
                return ResourceManager.GetString("elapsed_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Bearbeitung.
        /// </summary>
        public static string in_progress {
            get {
                return ResourceManager.GetString("in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string iso_code {
            get {
                return ResourceManager.GetString("iso_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte erfolgreiche Schreibposition.
        /// </summary>
        public static string last_successful_write {
            get {
                return ResourceManager.GetString("last_successful_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben das Limit an Geräten erreicht, die Sie hinzufügen können..
        /// </summary>
        public static string limit_reached {
            get {
                return ResourceManager.GetString("limit_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokale Laufwerke anzeigen.
        /// </summary>
        public static string local_disks {
            get {
                return ResourceManager.GetString("local_disks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehrgeräte-Prüfung.
        /// </summary>
        public static string multi_device {
            get {
                return ResourceManager.GetString("multi_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Update verfügbar..
        /// </summary>
        public static string new_update_available {
            get {
                return ResourceManager.GetString("new_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionen.
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vor. verbleibende Zeit.
        /// </summary>
        public static string remaining_time {
            get {
                return ResourceManager.GetString("remaining_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporäre Dateien entfernen, wenn fertiggestellt.
        /// </summary>
        public static string remove_temporary_files {
            get {
                return ResourceManager.GetString("remove_temporary_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text-Log auf Gerät speichern.
        /// </summary>
        public static string save_log_to_device {
            get {
                return ResourceManager.GetString("save_log_to_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle starten.
        /// </summary>
        public static string start_all {
            get {
                return ResourceManager.GetString("start_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiken.
        /// </summary>
        public static string stats {
            get {
                return ResourceManager.GetString("stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim ersten Fehler anhalten.
        /// </summary>
        public static string stop_on_first_failure {
            get {
                return ResourceManager.GetString("stop_on_first_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testergebnis:.
        /// </summary>
        public static string test_result {
            get {
                return ResourceManager.GetString("test_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfen.
        /// </summary>
        public static string verifying {
            get {
                return ResourceManager.GetString("verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warten....
        /// </summary>
        public static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warten auf Geräteauswahl....
        /// </summary>
        public static string waiting_for_device {
            get {
                return ResourceManager.GetString("waiting_for_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
